### ISSUE TITLE
ДЗ №3

### ISSUE THREAD

**Issue by skubik** [MIEE-ACS/domashnee-zadanie-no3-skubik#1]
Здравствуйте! Я выполнил задание.

**Comment by skubik** [comment]
Мой вариант № 3.

**Comment by d-makarenko** [comment]
Не правильно обрабатываются краевые моменты - а превращается в Я, я превращается в Ю и тд.
Но в целом все правильно.
4-

![2018-10-29 23_17_20-window](https://user-images.githubusercontent.com/31288426/47678130-16fb8e80-dbd2-11e8-9e6c-5947aa78a4dd.png)
